### ISSUE TITLE
多边形添加控制点判断有漏洞

### ISSUE THREAD

**Issue by mahu032** [heylight/canvas-select#101]
![image](https://github.com/heylight/canvas-select/assets/29297562/8d33d3e1-5af8-442b-8239-367869070d4f)
if ([2, 4].includes(this.activeShape.type)) {
                        const [x, y] = this.activeShape.coor[this.activeShape.coor.length - 1];
                        if (x !== offsetX && y !== offsetY) {
                            const nx = Math.round(offsetX - this.originX / this.scale);
                            const ny = Math.round(offsetY - this.originY / this.scale);
                            // this.activeShape.coor.push([nx, ny]);
                            // 添加点判断虽然有判断坐标偏移(坐标是浮点数, 不同的浮点数四舍五入结果可能一样)--实际添加的是四舍五入后的点坐标
                            // 还需要再次判断已有点是否和添加的点重复
                            if (!this.activeShape.coor.some((p:Point) => p[0] === nx && p[1] === ny)) {                                
                                this.activeShape.coor.push([nx, ny]);
                            }
                        }
                    }

**Comment by heylight** [comment]
你好

**Comment by heylight** [comment]
你好，
