### ISSUE TITLE
2.19版本 避免键盘事件被阻止 这个是什么功能

### ISSUE THREAD

**Issue by qq1114127270** [heylight/canvas-select#104]
自己写的监听keyup失效了

**Comment by heylight** [comment]
你的监听keyup代码发出来看看

**Comment by qq1114127270** [comment]
> 你的监听keyup代码发出来看看

![微信截图_20240416101241](https://github.com/heylight/canvas-select/assets/62101318/f883797a-7b60-434a-990a-ca1e463fdc31)
按住ctrl的时候可以拖拽 放开可以绘制

**Comment by heylight** [comment]
keyup默认被canvas-select阻止事件冒泡了，你仍然可以通过捕获方式获取事件：

```js
document.body.addEventListener('keyup', (e) => {
      instance.createType = 1
},true)
```
