### ISSUE TITLE
如何对控制点添加自定义样式以及hover事件

### ISSUE THREAD

**Issue by jockered** [heylight/canvas-select#109]
想要实现一个功能 : 鼠标移动到控制点时,变为可点击状态.目前似乎没有可以控制的入口

**Comment by heylight** [comment]
控制点自定义样式参考文档。hover事件影响性能，且不是刚需，暂不引入

**Comment by jockered** [comment]
好的 感谢您的回答💞

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: heylight ***@***.***>
发送时间: Wednesday, April 24, 2024 4:55:16 PM
收件人: heylight/canvas-select ***@***.***>
抄送: jocker ***@***.***>; Author ***@***.***>
主题: Re: [heylight/canvas-select] 如何对控制点添加自定义样式以及hover事件 (Issue #109)


控制点自定义样式参考文档。hover事件影响性能，且不是刚需，暂不引入
