### ISSUE TITLE
ctrlKey 的状态可能不正确，建议开放 ctrlKey 修改

### ISSUE THREAD

**Issue by lzhida** [heylight/canvas-select#121]
我是在electron 的环境中使用这个库的，由于可能出现按`ctrl + `的快捷键打开其他窗口，会导致窗口焦点转移，keyup 事件可能不会触发。

当添加新的 shape时，无法绘制，需要重新按下 ctrl 按键修改 ctrlKey  的状态

**Comment by heylight** [comment]
你好，先试用v2.23.0-beta.0能否满足需求
全局属性ctrlCode默认ControlLeft，可以自定义修改，value类型为KeyboardEvent.code

**Comment by heylight** [comment]
我把v2.23.0-beta.0发到了npm，刚把2.23.0的git分支也推上去了。
你也可以根据实际需求自己修改，欢迎提PR。
