### ISSUE TITLE
发现一个bug：单个形状设置hide为true后，点击无法正常选中标签了

### ISSUE THREAD

**Issue by Z20163132** [heylight/canvas-select#141]

**Comment by heylight** [comment]
hide设置为true后，这个形状就应该不展示了。你这里怎么还能点击呢？设置后没有update？

**Comment by Z20163132** [comment]
比如画了5个矩形框，其他有一个设置hide为true，这一个不显示了，其他4个还显示，不能正常选中其他4个了

**Comment by Z20163132** [comment]
比如画了5个矩形框，其中有一个设置hide为true，这一个不显示了，其他4个还显示，不能正常选中其他4个了

**Comment by Z20163132** [comment]
尤其是设置hide为true的那个矩形框非常大，大到会遮盖其他4个矩形框时，虽然设置hide为true的那个矩形框不显示了，但还是会遮盖其他4个框，其他4个框无法选中

**Comment by Z20163132** [comment]
select事件进行选中时，应该除去hide为true的数据，这样就能选中显示的数据了，不会被遮挡了

**Comment by Z20163132** [comment]
没有开启创建状态

**Comment by heylight** [comment]
已修复，请更新v2.23.1试一下吧

**Comment by Z20163132** [comment]
可以了，问题已解决
