### ISSUE TITLE
发现一个bug：labelMaxLen为什么设置了不生效呢？

### ISSUE THREAD

**Issue by Z20163132** [heylight/canvas-select#142]

**Comment by heylight** [comment]
labelMaxLen只对全局生效，当时考虑的是在单个图形设置意义不大

**Comment by heylight** [comment]
![image](https://github.com/user-attachments/assets/7a9feee8-8e15-427f-8037-caa5651f5981)

**Comment by Z20163132** [comment]
我就是全局设置的，但是没有生效

**Comment by Z20163132** [comment]
查看示例demo中，我试的，labelMaxLen也不生效；
您再看看

**Comment by heylight** [comment]
> 查看示例demo中，我试的，labelMaxLen也不生效； 您再看看

我尝试修改示例demo，是正常的
![image](https://github.com/user-attachments/assets/a272458f-96d6-4252-bbe8-1b2e646e6af3)

**Comment by Z20163132** [comment]
可以了，问题已解决
