### ISSUE TITLE
在VUE中一直提示"HTMLCanvasElement is required!"

### ISSUE THREAD

**Issue by jvhuaiying** [heylight/canvas-select#18]
<template>
      <main>
        <div class="part0"></div>
        <div class="part1">
          <canvas class="can0"></canvas>
        </div>
        <div class="part2">
          <div></div>
          <div></div>
        </div>
      </main>
    </template>
    
    <script setup>
    import {watch} from "vue";
    import CanvasSelect from "canvas-select";
    
    const can1 = new CanvasSelect('can0', 'https://unpkg.com/canvas-select@2.3.4/one.jpg');
    let props = defineProps({
      int0: {
        type: Number,
        default: 0
      }
    });
    watch(props, (val) => {
      console.log(val.int0);
    });
    </script>

**Comment by heylight** [comment]
CanvasSelect的第一个参数可以是css选择器，也可以是一个dom对象

**Comment by heylight** [comment]
CanvasSelect的第一个参数既可以是css选择器，也可以是一个dom对象。你这里需要把"can0"改成".can0"
