### ISSUE TITLE
请问可以支持移动端的缩放和拖拽吗

### ISSUE THREAD

**Issue by niuwanjun** [heylight/canvas-select#25]

**Comment by heylight** [comment]
计划下一个版本支持

**Comment by niuwanjun** [comment]
非常期待

**Comment by heylight** [comment]
感谢关注，现已支持移动端，请使用v2.9.0版本。

**Comment by niuwanjun** [comment]
请问可以支持限制图片拖拽范围和设置初始、最大、最小缩放值吗（使用场景：移动端加载图片全屏展示，上下左右拖拽时与边界之间不留间隙）？

**Comment by heylight** [comment]
> 请问可以支持限制图片拖拽范围和设置初始、最大、最小缩放值吗（使用场景：移动端加载图片全屏展示，上下左右拖拽时与边界之间不留间隙）？

1. 当前图片在画布中初始状态已经做了全屏适配(contain)。而且移动缩放之后也可以通过fitZoom()重置。
2. 图片缩放最小值50px，最大值是图片最大边尺寸的10倍，基本满足用户使用需求。

以上，个人觉得需求收益不大。

**Comment by niuwanjun** [comment]
了解了
