### ISSUE TITLE
已标注内容选中问题

### ISSUE THREAD

**Issue by jvhuaiying** [heylight/canvas-select#34]
新版本在调用change(1-5)之后，需要调用change(0)，点击标注图形内部才能选中已标注内容，建议可以考虑跳过change(0)的步骤，在”创建模式“下点击已标注内容内部来实现对已标注内容的选中。
感谢大神维护了如此优秀的项目！

**Comment by heylight** [comment]
如果按照你的想法，在已经创建标注的区域内就无法再进行创建了，这也是为什么新的版本会把创建模式和拖动模式分开的原因。

**Comment by jvhuaiying** [comment]
> 如果按照你的想法，在已经创建标注的区域内就无法再进行创建了，这也是为什么新的版本会把创建模式和拖动模式分开的原因。
> 
> 在功能性和便捷性问题上，应该倾向于功能性。

同意大佬的看法，毕竟本项目是作为工具而存在的，更多的应当着重于实现功能，具体的便捷性可以交给使用者来优化
