### ISSUE TITLE
动态切换图片

### ISSUE THREAD

**Issue by zhaoxuefei-ai** [heylight/canvas-select#4]
在有框选区域时，动态切换图片后，点击切换后的图片上的框选区域会跳到上一张图片，再次点击会又跳回去

**Comment by zhaoxuefei-ai** [comment]
index.ts 文件 287行 改成这样
if (x < 0 || x > w || y < 0 || y > h) return this.update();

**Comment by heylight** [comment]
> index.ts 文件 287行 改成这样 if (x < 0 || x > w || y < 0 || y > h) return this.update();

已优化

**Comment by heylight** [comment]
> 在有框选区域时，动态切换图片后，点击切换后的图片上的框选区域会跳到上一张图片，再次点击会又跳回去

建议创建新实例的方式切换图片

> 在有框选区域时，动态切换图片后，点击切换后的图片上的框选区域会跳到上一张图片，再次点击会又跳回去

新版已修复，请使用setImage方法切换图片

**Comment by heylight** [comment]
> 在有框选区域时，动态切换图片后，点击切换后的图片上的框选区域会跳到上一张图片，再次点击会又跳回去

新版已修复，请使用setImage方法切换图片
