### ISSUE TITLE
【功能】清空所有的标注

### ISSUE THREAD

**Issue by ChunMengLu** [heylight/canvas-select#40]
希望能添加一个方法可以直接清空所有标注，现在只能一个个删除或者destroy掉

**Comment by heylight** [comment]
换一个角度，尝试使用setData([])来清空所有标注吧

**Comment by ChunMengLu** [comment]
> 换一个角度，尝试使用setData([])来清空所有标注吧

试过，好像没清理掉，我明天再试一把看看
