### ISSUE TITLE
嵌套图形选中的Bug

### ISSUE THREAD

**Issue by jvhuaiying** [heylight/canvas-select#44]
大神您好，我们在实际开发中发现，当标注区域A位于B内部的时候，只有在不选中B的情况下才能够选中A，只要曾经选中过B，则无论如何均无法选中A。感谢大神！

**Comment by heylight** [comment]
最新版本，在没有选中任何标注区域的情况下，则恢复图层原有的层级关系

**Comment by jvhuaiying** [comment]
感谢大神！
