### ISSUE TITLE
锁定画布

### ISSUE THREAD

**Issue by JudgeFFF** [heylight/canvas-select#47]
锁定画布为何无法编辑标注

**Comment by heylight** [comment]
锁定画布功能的初衷是将整个画布只作为展示结果来用，不允许任何操作，可以视为一个静态图片。

**Comment by JudgeFFF** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
