### ISSUE TITLE
新版本如何确定每次框选结束的时机呢？

### ISSUE THREAD

**Issue by jiangjiangpeng** [heylight/canvas-select#48]
如果监听update或者instance.dataset,框在变化的时候，每时每刻都在调用。我想要的是结束框选之后的时机，

**Comment by jiangjiangpeng** [comment]
我目前是在update的监听中直接instance.createType = 0，会有点击创建矩形框按钮后，伸缩页面直接update instance.createType = 0的难点。所以还是希望有一个结束框选的时机，应该是处在新版select时机之前的

**Comment by heylight** [comment]
每次结束框选会触发add事件
```js
instace.on("add",shape=>{})
```
