### ISSUE TITLE
请教大佬 如何设置固定尺寸

### ISSUE THREAD

**Issue by tjt740** [heylight/canvas-select#50]
如题：
  我看到实例上有 instance.scale 的属性能拿到具体尺寸，但是setScale()方法貌似不支持设置比例大小，只能通过设置ture不断增大尺寸。

**Comment by tjt740** [comment]
我是用在nlp平台上的 ，想着每次刷新组件的方式 去实现数据的最新状态，带来的弊端就是无法保证以前的页面尺寸

**Comment by heylight** [comment]
如果画布上的图片没有变化，只是数据更新了，那么直接通过setData(data)更新新数据就行，图片缩放比例和移动位置都会保持不变
