### ISSUE TITLE
形状边线可以自定义颜色，如何自定义线的宽度？

### ISSUE THREAD

**Issue by Jeson-gk** [heylight/canvas-select#53]
形状边线可以自定义颜色，如何自定义线的宽度？

**Comment by catnuko** [comment]
<img width="1866" height="843" alt="Image" src="https://github.com/user-attachments/assets/58e5de6b-16c3-4381-8861-365525ddd1f5" />为什么lineWidth会控制其中一部分图像的线宽呢？
