### ISSUE TITLE
加载图片后报错

### ISSUE THREAD

**Issue by CodorMonkey** [heylight/canvas-select#60]
![image](https://github.com/heylight/canvas-select/assets/14367510/17476136-f2e7-438c-bf2e-9217efe4aeca)
使用图片大小如上图所示

报错信息如下图所示
![image](https://github.com/heylight/canvas-select/assets/14367510/ac76303a-aa63-49de-a1ff-3a3313522965)

**Comment by heylight** [comment]
可以提供一下原图文件吗？

**Comment by CodorMonkey** [comment]
![Image_20230630143116408image_1](https://github.com/heylight/canvas-select/assets/14367510/66527a41-6990-4a10-9158-c6ecae34f3af)

@heylight 不好意思，这几天太忙忘记这事了，上图就是测试用的原图

**Comment by heylight** [comment]
bug产生的原因：
原本规定图片最小边长缩放不能小于50，但是这个图片本身最小边长是48，递归没有终止条件导致内存泄露。
现已修复，请使用v2.14.1

**Comment by CodorMonkey** [comment]
好的，感谢回复
