### ISSUE TITLE
2.14.1版本使用问题

### ISSUE THREAD

**Issue by jessie717** [heylight/canvas-select#64]
类型接口不统一

这是我当前使用版本：
` "canvas-select": "^2.14.1"`

这是`2.14.1`版本的类型：
![image](https://github.com/heylight/canvas-select/assets/45997116/90fcaa48-ab73-4d50-8c70-1b34ee346a19)

但是github上的源码上暴露出来的：
![image](https://github.com/heylight/canvas-select/assets/45997116/4141276b-fee1-49a1-b167-622dbbbb893c)

因为是配合了ts的使用，需要用到相应的类型，后续版本还望能够将相应类型暴露出来供使用

谢谢！

**Comment by heylight** [comment]
欢迎提PR :)
