### ISSUE TITLE
屏闪问题

### ISSUE THREAD

**Issue by jessie717** [heylight/canvas-select#65]
使用环境：
 vue3.2 + vite4.3

问题呈现：
canvas标签在template中固定时，通过ref获取到canvas后，绘制正常；
动态更新src后，`mousedown`时就会一直屏闪复现上一图层标注后的shape

**Comment by jessie717** [comment]
我目前的解决方案时，动态创建canvas标签是没有这个屏闪问题的

**Comment by heylight** [comment]
建议动态更换图片的时候也清空一下上一次的标注数据

**Comment by heylight** [comment]
你是通过什么方式动态更新src的呢？

**Comment by jessie717** [comment]
> 你是通过什么方式动态更新src的呢？

我是动态创建canvas标签，在更新src前，先去抓取下canvas是否存在，存在就删除动态创建一个新的canvas标签，这也就能做到canvas<->src动态一对一绑定，不会屏闪。
有没有更好的方法去处理这个啊？

**Comment by heylight** [comment]
是通过setImage更换图片之后开始闪屏的吗？
