### ISSUE TITLE
谢谢作者，看到这个项目，我毫不犹豫地点了一个小星星，有个问题咨询下，我如何获取到当前选中的标记。

### ISSUE THREAD

**Issue by songdemei** [heylight/canvas-select#68]
我的需求是，如果在按一下删除键，这时如果选中了某个标签，我就把这个标签删除掉，现在有选中事件，但如果我选中一个标签，然后又点了一下图片，这时所有图片都未选中，但这时并没有事件触发，如果这是按了一下删除键，但这时我又不知道这个标签是不是实际选中状态的，所以我不知道该不该删除这个标签，不知道我说明白了没。辛苦作者了，谢谢！

**Comment by songdemei** [comment]
还有个事件，就是标记的双击事件，
双击我想做成弹出一个界面，可以修改颜色和文字啥的，现在只有选中事件，选中弹出不合适，因为选中还会有别的操作，不一定是修改标签和颜色

**Comment by heylight** [comment]
> 我的需求是，如果在按一下删除键，这时如果选中了某个标签，我就把这个标签删除掉，现在有选中事件，但如果我选中一个标签，然后又点了一下图片，这时所有图片都未选中，但这时并没有事件触发，如果这是按了一下删除键，但这时我又不知道这个标签是不是实际选中状态的，所以我不知道该不该删除这个标签，不知道我说明白了没。辛苦作者了，谢谢！

你好，你可以给canvas标签绑定一个点击事件，这样点击画布上任何地方都会触发一个事件，然后通过instance.activeShape获取当前选中的标签状态(instance表示当前实例)。

**Comment by heylight** [comment]
> 



> 还有个事件，就是标记的双击事件， 双击我想做成弹出一个界面，可以修改颜色和文字啥的，现在只有选中事件，选中弹出不合适，因为选中还会有别的操作，不一定是修改标签和颜色

与上面的方法一样，你可以在canvas标签上绑定双击事件，获取instance.activeShape做一些修改操作。

**Comment by heylight** [comment]
> 还有个需求，就是希望能画剪头 ，就像微信截图，画个剪头，指向某个地方，这个也很重要，也很常用，希望能加上。谢谢！

这个需求我记下了，有时间再做😁
