### ISSUE TITLE
MAC触控板双指放大的时候会把页面也放大

### ISSUE THREAD

**Issue by wangyingjie123** [heylight/canvas-select#69]

**Comment by wangyingjie123** [comment]
mousewheel事件改成wheel事件就可以

**Comment by heylight** [comment]
通过系统设置吧，暂时没有找到其他办法
<img width="715" alt="image" src="https://github.com/heylight/canvas-select/assets/28283341/9757046b-6265-4a8d-b9ee-2f8449dde60a">
