### ISSUE TITLE
vue2中使用问题

### ISSUE THREAD

**Issue by chuzhu** [heylight/canvas-select#73]
目前在vue2中使用该组件，使用方式如下：
import CanvasSelect from 'canvas-select';

const instance = new CanvasSelect('.markup-container');
let option =  ...

 instance.setData(option);

其中，在调用setData时报错，异常信息如下：
![WX20231017-172135](https://github.com/heylight/canvas-select/assets/13775164/f119ba96-6241-4fef-9254-4c8d9b51a926)

请问这种情况该如何解决？在线等，谢谢

**Comment by heylight** [comment]
请在mounted中创建实例

**Comment by chuzhu** [comment]
> 请在mounted中创建实例

谢谢
