### ISSUE TITLE
safari 下图片稍大时标注会卡顿闪屏

### ISSUE THREAD

**Issue by liuxueyong123** [heylight/canvas-select#77]
每次 mousemove 均会清除图片以及标注，然后重新绘制图片和标注。是否考虑给 mousemove 事件加上节流，否则一次标注触发上百次重绘了

**Comment by heylight** [comment]
除了点标注，进行其他标注mousemove都有画布更新

**Comment by liuxueyong123** [comment]
但是目前更新频率应该是有点高，一次mousemove触发上百次重绘了。加上节流，比如1s只重绘60次，完全够了

**Comment by heylight** [comment]
你好，v2.16.1已经更新update方法，通过requestAnimationFrame来控制截流。

**Comment by liuxueyong123** [comment]
🎉
