### ISSUE TITLE
在查看模式下(createType: -1), 如何禁止对形状的删除和改变

### ISSUE THREAD

**Issue by jaykou25** [heylight/canvas-select#79]
首先感谢作者.

我现在有一个需求, 就是希望要有一个查看模式, 用户只能点击选中某个形状, 但是不能拖动, 改变, 删除形状.  但是在 createType为-1时, 用户确实不能拖动形状, 但是却可以删除和改变形状.

如果用 lock 模式的话, 虽然是不能删除和改变了, 但是用户也不能选中形状了, 同时也不能放大图片. 

想请教一下, 有什么办法能阻止用户的删除, 改变形状的形为吗?

**Comment by heylight** [comment]
你好，v2.17.0新增了readonly模式，可以试一下，欢迎反馈。
