### ISSUE TITLE
缩放比例不准确问题

### ISSUE THREAD

**Issue by zhanweiD** [heylight/canvas-select#87]
第一次调用setScale进行缩小时，缩小比例大于5%，导致再次调用setScale放大时，恢复不到原始比例，后续缩放比例正常。

**Comment by heylight** [comment]
缩放都是按照5%进行的，“缩小比例大于5%”是哪种情形？

**Comment by zhanweiD** [comment]
第一次调用setScale(false)时，示例也能够复现，图片本来是填充满的，点击一下缩小，再点击一下放大图片是没有填充满的

**Comment by heylight** [comment]
缩放都是按照5%进行的，但是不能保证按照这个比例能够刚好填充画布(contain)。初始化的时候，缩放需要优先保证填充画布，这个比例可能就不是5%了。之后的缩放由于不用考虑填充画布，就继续使用5%的比例。

**Comment by zhanweiD** [comment]
明白了谢谢
