### ISSUE TITLE
关于插件引入到vue3项目中，instance.on事件监听貌似失效了

### ISSUE THREAD

**Issue by fuyu0316** [heylight/canvas-select#88]

**Comment by heylight** [comment]
代码示例发一下吧

**Comment by fuyu0316** [comment]
`<template>
  <canvas class="container"></canvas>
</template>

<script lang="ts" setup>
import CanvasSelect from "canvas-select";
import { onMounted, ref } from "vue";

let instance: any = ref(null);
//图形标注列表
const option: any = ref([
  {
    // 标签
    label: "rect",
    // 点数据
    coor: [
      [184, 183],
      [275, 238],
    ],
    // 图形类型
    type: 1,
  },
  {
    label: "polygon",
    active: false,
    coor: [
      [135, 291],
      [129, 319],
      [146, 346],
      [174, 365],
      [214, 362],
      [196, 337],
      [161, 288],
    ],
    type: 2,
  },
  {
    label: "dot",
    coor: [345, 406],
    type: 3,
  },
  {
    label: "line",
    coor: [
      [456, 153],
      [489, 228],
      [492, 296],
    ],
    type: 4,
  },
  {
    label: "circle",
    coor: [369, 197],
    radius: 38,
    type: 5,
  },
]);
onMounted(() => {
  //创建实例
  instance = new CanvasSelect(".container", "../assets/hide.png");
  // 标签最大长度
  instance.labelMaxLen = 10;
  // 图形数据赋值到实例
  instance.setData(option.value);
  console.log(instance);

  // 选中
  instance.on("select", (shape: any) => {
    console.log("select", shape);
  });
});
</script>`

基本就是文档示例代码，运行之后instance中能绑定select监听事件，但是鼠标点击图形之后没反应，控制台不输出信息
