### ISSUE TITLE
label事件

### ISSUE THREAD

**Issue by anzaiok** [heylight/canvas-select#93]
建议作者添加标签label的鼠标选中事件

**Comment by heylight** [comment]
和直接选中标注图形有什么区别么。。。

**Comment by anzaiok** [comment]
区别大了去了，试想一下，如果你画的是一根很细的线或者点，那选择图形是不是很困难，选择标注的label是不是很容易就选中了？

**Comment by heylight** [comment]
关于你提到的选择困难的问题，本身已有优化

1. 一条线的宽度是1像素，但是鼠标点击的热区实际宽度是5像素
2. 点标注可以通过设置ctrlRadius(默认是3)来调整鼠标点击热区大小
3. 通过点击标签去选中标注图形可能会让一部分用户产生歧义

**Comment by anzaiok** [comment]
我试了下你说得方法，效果都不怎么好，我建议可以把点击标签选中图形做成配置选项让用户去配置，默认不生效
